// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// UserInput is an autogenerated mock type for the UserInput type
type UserInput struct {
	mock.Mock
}

type UserInput_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInput) EXPECT() *UserInput_Expecter {
	return &UserInput_Expecter{mock: &_m.Mock}
}

// GetFloatValue provides a mock function with given fields: message, minValue, maxValue
func (_m *UserInput) GetFloatValue(message string, minValue float64, maxValue float64) (float64, error) {
	ret := _m.Called(message, minValue, maxValue)

	if len(ret) == 0 {
		panic("no return value specified for GetFloatValue")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64, float64) (float64, error)); ok {
		return rf(message, minValue, maxValue)
	}
	if rf, ok := ret.Get(0).(func(string, float64, float64) float64); ok {
		r0 = rf(message, minValue, maxValue)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64, float64) error); ok {
		r1 = rf(message, minValue, maxValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInput_GetFloatValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloatValue'
type UserInput_GetFloatValue_Call struct {
	*mock.Call
}

// GetFloatValue is a helper method to define mock.On call
//   - message string
//   - minValue float64
//   - maxValue float64
func (_e *UserInput_Expecter) GetFloatValue(message interface{}, minValue interface{}, maxValue interface{}) *UserInput_GetFloatValue_Call {
	return &UserInput_GetFloatValue_Call{Call: _e.mock.On("GetFloatValue", message, minValue, maxValue)}
}

func (_c *UserInput_GetFloatValue_Call) Run(run func(message string, minValue float64, maxValue float64)) *UserInput_GetFloatValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *UserInput_GetFloatValue_Call) Return(_a0 float64, _a1 error) *UserInput_GetFloatValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInput_GetFloatValue_Call) RunAndReturn(run func(string, float64, float64) (float64, error)) *UserInput_GetFloatValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntValue provides a mock function with given fields: message, minValue, maxValue
func (_m *UserInput) GetIntValue(message string, minValue int, maxValue int) (int, error) {
	ret := _m.Called(message, minValue, maxValue)

	if len(ret) == 0 {
		panic("no return value specified for GetIntValue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (int, error)); ok {
		return rf(message, minValue, maxValue)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) int); ok {
		r0 = rf(message, minValue, maxValue)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(message, minValue, maxValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInput_GetIntValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntValue'
type UserInput_GetIntValue_Call struct {
	*mock.Call
}

// GetIntValue is a helper method to define mock.On call
//   - message string
//   - minValue int
//   - maxValue int
func (_e *UserInput_Expecter) GetIntValue(message interface{}, minValue interface{}, maxValue interface{}) *UserInput_GetIntValue_Call {
	return &UserInput_GetIntValue_Call{Call: _e.mock.On("GetIntValue", message, minValue, maxValue)}
}

func (_c *UserInput_GetIntValue_Call) Run(run func(message string, minValue int, maxValue int)) *UserInput_GetIntValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UserInput_GetIntValue_Call) Return(_a0 int, _a1 error) *UserInput_GetIntValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInput_GetIntValue_Call) RunAndReturn(run func(string, int, int) (int, error)) *UserInput_GetIntValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringValue provides a mock function with given fields: message
func (_m *UserInput) GetStringValue(message string) (string, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for GetStringValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInput_GetStringValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringValue'
type UserInput_GetStringValue_Call struct {
	*mock.Call
}

// GetStringValue is a helper method to define mock.On call
//   - message string
func (_e *UserInput_Expecter) GetStringValue(message interface{}) *UserInput_GetStringValue_Call {
	return &UserInput_GetStringValue_Call{Call: _e.mock.On("GetStringValue", message)}
}

func (_c *UserInput_GetStringValue_Call) Run(run func(message string)) *UserInput_GetStringValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserInput_GetStringValue_Call) Return(_a0 string, _a1 error) *UserInput_GetStringValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInput_GetStringValue_Call) RunAndReturn(run func(string) (string, error)) *UserInput_GetStringValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeValue provides a mock function with given fields: message
func (_m *UserInput) GetTimeValue(message string) (time.Time, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeValue")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (time.Time, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInput_GetTimeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeValue'
type UserInput_GetTimeValue_Call struct {
	*mock.Call
}

// GetTimeValue is a helper method to define mock.On call
//   - message string
func (_e *UserInput_Expecter) GetTimeValue(message interface{}) *UserInput_GetTimeValue_Call {
	return &UserInput_GetTimeValue_Call{Call: _e.mock.On("GetTimeValue", message)}
}

func (_c *UserInput_GetTimeValue_Call) Run(run func(message string)) *UserInput_GetTimeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserInput_GetTimeValue_Call) Return(_a0 time.Time, _a1 error) *UserInput_GetTimeValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInput_GetTimeValue_Call) RunAndReturn(run func(string) (time.Time, error)) *UserInput_GetTimeValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserInput creates a new instance of UserInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInput(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInput {
	mock := &UserInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
