// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Importer is an autogenerated mock type for the Importer type
type Importer struct {
	mock.Mock
}

type Importer_Expecter struct {
	mock *mock.Mock
}

func (_m *Importer) EXPECT() *Importer_Expecter {
	return &Importer_Expecter{mock: &_m.Mock}
}

// Import provides a mock function with given fields: fileName
func (_m *Importer) Import(fileName string) (interface{}, error) {
	ret := _m.Called(fileName)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(fileName)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Importer_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type Importer_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - fileName string
func (_e *Importer_Expecter) Import(fileName interface{}) *Importer_Import_Call {
	return &Importer_Import_Call{Call: _e.mock.On("Import", fileName)}
}

func (_c *Importer_Import_Call) Run(run func(fileName string)) *Importer_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Importer_Import_Call) Return(_a0 interface{}, _a1 error) *Importer_Import_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Importer_Import_Call) RunAndReturn(run func(string) (interface{}, error)) *Importer_Import_Call {
	_c.Call.Return(run)
	return _c
}

// NewImporter creates a new instance of Importer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Importer {
	mock := &Importer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
