// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

type AnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsService) EXPECT() *AnalyticsService_Expecter {
	return &AnalyticsService_Expecter{mock: &_m.Mock}
}

// CalculateBalance provides a mock function with no fields
func (_m *AnalyticsService) CalculateBalance() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CalculateBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_CalculateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateBalance'
type AnalyticsService_CalculateBalance_Call struct {
	*mock.Call
}

// CalculateBalance is a helper method to define mock.On call
func (_e *AnalyticsService_Expecter) CalculateBalance() *AnalyticsService_CalculateBalance_Call {
	return &AnalyticsService_CalculateBalance_Call{Call: _e.mock.On("CalculateBalance")}
}

func (_c *AnalyticsService_CalculateBalance_Call) Run(run func()) *AnalyticsService_CalculateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AnalyticsService_CalculateBalance_Call) Return(_a0 float64, _a1 error) *AnalyticsService_CalculateBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_CalculateBalance_Call) RunAndReturn(run func() (float64, error)) *AnalyticsService_CalculateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateBalanceDifference provides a mock function with no fields
func (_m *AnalyticsService) CalculateBalanceDifference() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CalculateBalanceDifference")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_CalculateBalanceDifference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateBalanceDifference'
type AnalyticsService_CalculateBalanceDifference_Call struct {
	*mock.Call
}

// CalculateBalanceDifference is a helper method to define mock.On call
func (_e *AnalyticsService_Expecter) CalculateBalanceDifference() *AnalyticsService_CalculateBalanceDifference_Call {
	return &AnalyticsService_CalculateBalanceDifference_Call{Call: _e.mock.On("CalculateBalanceDifference")}
}

func (_c *AnalyticsService_CalculateBalanceDifference_Call) Run(run func()) *AnalyticsService_CalculateBalanceDifference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AnalyticsService_CalculateBalanceDifference_Call) Return(_a0 float64, _a1 error) *AnalyticsService_CalculateBalanceDifference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_CalculateBalanceDifference_Call) RunAndReturn(run func() (float64, error)) *AnalyticsService_CalculateBalanceDifference_Call {
	_c.Call.Return(run)
	return _c
}

// RecalculateBalances provides a mock function with no fields
func (_m *AnalyticsService) RecalculateBalances() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RecalculateBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnalyticsService_RecalculateBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecalculateBalances'
type AnalyticsService_RecalculateBalances_Call struct {
	*mock.Call
}

// RecalculateBalances is a helper method to define mock.On call
func (_e *AnalyticsService_Expecter) RecalculateBalances() *AnalyticsService_RecalculateBalances_Call {
	return &AnalyticsService_RecalculateBalances_Call{Call: _e.mock.On("RecalculateBalances")}
}

func (_c *AnalyticsService_RecalculateBalances_Call) Run(run func()) *AnalyticsService_RecalculateBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AnalyticsService_RecalculateBalances_Call) Return(_a0 error) *AnalyticsService_RecalculateBalances_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnalyticsService_RecalculateBalances_Call) RunAndReturn(run func() error) *AnalyticsService_RecalculateBalances_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
