// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// BankAccountService is an autogenerated mock type for the BankAccountService type
type BankAccountService struct {
	mock.Mock
}

type BankAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *BankAccountService) EXPECT() *BankAccountService_Expecter {
	return &BankAccountService_Expecter{mock: &_m.Mock}
}

// CreateBankAccount provides a mock function with given fields: account
func (_m *BankAccountService) CreateBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BankAccountService_CreateBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBankAccount'
type BankAccountService_CreateBankAccount_Call struct {
	*mock.Call
}

// CreateBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *BankAccountService_Expecter) CreateBankAccount(account interface{}) *BankAccountService_CreateBankAccount_Call {
	return &BankAccountService_CreateBankAccount_Call{Call: _e.mock.On("CreateBankAccount", account)}
}

func (_c *BankAccountService_CreateBankAccount_Call) Run(run func(account *domain.BankAccount)) *BankAccountService_CreateBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *BankAccountService_CreateBankAccount_Call) Return(_a0 error) *BankAccountService_CreateBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BankAccountService_CreateBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *BankAccountService_CreateBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBankAccount provides a mock function with given fields: id
func (_m *BankAccountService) DeleteBankAccount(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BankAccountService_DeleteBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBankAccount'
type BankAccountService_DeleteBankAccount_Call struct {
	*mock.Call
}

// DeleteBankAccount is a helper method to define mock.On call
//   - id int
func (_e *BankAccountService_Expecter) DeleteBankAccount(id interface{}) *BankAccountService_DeleteBankAccount_Call {
	return &BankAccountService_DeleteBankAccount_Call{Call: _e.mock.On("DeleteBankAccount", id)}
}

func (_c *BankAccountService_DeleteBankAccount_Call) Run(run func(id int)) *BankAccountService_DeleteBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *BankAccountService_DeleteBankAccount_Call) Return(_a0 error) *BankAccountService_DeleteBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BankAccountService_DeleteBankAccount_Call) RunAndReturn(run func(int) error) *BankAccountService_DeleteBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetBankAccount provides a mock function with given fields: id
func (_m *BankAccountService) GetBankAccount(id int) (*domain.BankAccount, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBankAccount")
	}

	var r0 *domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.BankAccount, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.BankAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankAccountService_GetBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBankAccount'
type BankAccountService_GetBankAccount_Call struct {
	*mock.Call
}

// GetBankAccount is a helper method to define mock.On call
//   - id int
func (_e *BankAccountService_Expecter) GetBankAccount(id interface{}) *BankAccountService_GetBankAccount_Call {
	return &BankAccountService_GetBankAccount_Call{Call: _e.mock.On("GetBankAccount", id)}
}

func (_c *BankAccountService_GetBankAccount_Call) Run(run func(id int)) *BankAccountService_GetBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *BankAccountService_GetBankAccount_Call) Return(_a0 *domain.BankAccount, _a1 error) *BankAccountService_GetBankAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BankAccountService_GetBankAccount_Call) RunAndReturn(run func(int) (*domain.BankAccount, error)) *BankAccountService_GetBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBankAccount provides a mock function with given fields: account
func (_m *BankAccountService) UpdateBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BankAccountService_UpdateBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBankAccount'
type BankAccountService_UpdateBankAccount_Call struct {
	*mock.Call
}

// UpdateBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *BankAccountService_Expecter) UpdateBankAccount(account interface{}) *BankAccountService_UpdateBankAccount_Call {
	return &BankAccountService_UpdateBankAccount_Call{Call: _e.mock.On("UpdateBankAccount", account)}
}

func (_c *BankAccountService_UpdateBankAccount_Call) Run(run func(account *domain.BankAccount)) *BankAccountService_UpdateBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *BankAccountService_UpdateBankAccount_Call) Return(_a0 error) *BankAccountService_UpdateBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BankAccountService_UpdateBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *BankAccountService_UpdateBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewBankAccountService creates a new instance of BankAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankAccountService {
	mock := &BankAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
