// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

type CategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryService) EXPECT() *CategoryService_Expecter {
	return &CategoryService_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function with given fields: category
func (_m *CategoryService) CreateCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryService_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type CategoryService_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *CategoryService_Expecter) CreateCategory(category interface{}) *CategoryService_CreateCategory_Call {
	return &CategoryService_CreateCategory_Call{Call: _e.mock.On("CreateCategory", category)}
}

func (_c *CategoryService_CreateCategory_Call) Run(run func(category *domain.Category)) *CategoryService_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *CategoryService_CreateCategory_Call) Return(_a0 error) *CategoryService_CreateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryService_CreateCategory_Call) RunAndReturn(run func(*domain.Category) error) *CategoryService_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: id
func (_m *CategoryService) DeleteCategory(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryService_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type CategoryService_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - id int
func (_e *CategoryService_Expecter) DeleteCategory(id interface{}) *CategoryService_DeleteCategory_Call {
	return &CategoryService_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", id)}
}

func (_c *CategoryService_DeleteCategory_Call) Run(run func(id int)) *CategoryService_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *CategoryService_DeleteCategory_Call) Return(_a0 error) *CategoryService_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryService_DeleteCategory_Call) RunAndReturn(run func(int) error) *CategoryService_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function with given fields: id
func (_m *CategoryService) GetCategory(id int) (*domain.Category, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryService_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type CategoryService_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - id int
func (_e *CategoryService_Expecter) GetCategory(id interface{}) *CategoryService_GetCategory_Call {
	return &CategoryService_GetCategory_Call{Call: _e.mock.On("GetCategory", id)}
}

func (_c *CategoryService_GetCategory_Call) Run(run func(id int)) *CategoryService_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *CategoryService_GetCategory_Call) Return(_a0 *domain.Category, _a1 error) *CategoryService_GetCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryService_GetCategory_Call) RunAndReturn(run func(int) (*domain.Category, error)) *CategoryService_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: category
func (_m *CategoryService) UpdateCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryService_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type CategoryService_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *CategoryService_Expecter) UpdateCategory(category interface{}) *CategoryService_UpdateCategory_Call {
	return &CategoryService_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", category)}
}

func (_c *CategoryService_UpdateCategory_Call) Run(run func(category *domain.Category)) *CategoryService_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *CategoryService_UpdateCategory_Call) Return(_a0 error) *CategoryService_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryService_UpdateCategory_Call) RunAndReturn(run func(*domain.Category) error) *CategoryService_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
