// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	exporter "github.com/AFK068/bot/internal/infrastructure/exporter"

	importer "github.com/AFK068/bot/internal/infrastructure/importer"

	mock "github.com/stretchr/testify/mock"
)

// DataService is an autogenerated mock type for the DataService type
type DataService struct {
	mock.Mock
}

type DataService_Expecter struct {
	mock *mock.Mock
}

func (_m *DataService) EXPECT() *DataService_Expecter {
	return &DataService_Expecter{mock: &_m.Mock}
}

// ExportBankAccounts provides a mock function with given fields: visitor, fileName
func (_m *DataService) ExportBankAccounts(visitor exporter.Exporter, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ExportBankAccounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(exporter.Exporter, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ExportBankAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportBankAccounts'
type DataService_ExportBankAccounts_Call struct {
	*mock.Call
}

// ExportBankAccounts is a helper method to define mock.On call
//   - visitor exporter.Exporter
//   - fileName string
func (_e *DataService_Expecter) ExportBankAccounts(visitor interface{}, fileName interface{}) *DataService_ExportBankAccounts_Call {
	return &DataService_ExportBankAccounts_Call{Call: _e.mock.On("ExportBankAccounts", visitor, fileName)}
}

func (_c *DataService_ExportBankAccounts_Call) Run(run func(visitor exporter.Exporter, fileName string)) *DataService_ExportBankAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(exporter.Exporter), args[1].(string))
	})
	return _c
}

func (_c *DataService_ExportBankAccounts_Call) Return(_a0 error) *DataService_ExportBankAccounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ExportBankAccounts_Call) RunAndReturn(run func(exporter.Exporter, string) error) *DataService_ExportBankAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ExportCategories provides a mock function with given fields: visitor, fileName
func (_m *DataService) ExportCategories(visitor exporter.Exporter, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ExportCategories")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(exporter.Exporter, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ExportCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCategories'
type DataService_ExportCategories_Call struct {
	*mock.Call
}

// ExportCategories is a helper method to define mock.On call
//   - visitor exporter.Exporter
//   - fileName string
func (_e *DataService_Expecter) ExportCategories(visitor interface{}, fileName interface{}) *DataService_ExportCategories_Call {
	return &DataService_ExportCategories_Call{Call: _e.mock.On("ExportCategories", visitor, fileName)}
}

func (_c *DataService_ExportCategories_Call) Run(run func(visitor exporter.Exporter, fileName string)) *DataService_ExportCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(exporter.Exporter), args[1].(string))
	})
	return _c
}

func (_c *DataService_ExportCategories_Call) Return(_a0 error) *DataService_ExportCategories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ExportCategories_Call) RunAndReturn(run func(exporter.Exporter, string) error) *DataService_ExportCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ExportOperations provides a mock function with given fields: visitor, fileName
func (_m *DataService) ExportOperations(visitor exporter.Exporter, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ExportOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(exporter.Exporter, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ExportOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportOperations'
type DataService_ExportOperations_Call struct {
	*mock.Call
}

// ExportOperations is a helper method to define mock.On call
//   - visitor exporter.Exporter
//   - fileName string
func (_e *DataService_Expecter) ExportOperations(visitor interface{}, fileName interface{}) *DataService_ExportOperations_Call {
	return &DataService_ExportOperations_Call{Call: _e.mock.On("ExportOperations", visitor, fileName)}
}

func (_c *DataService_ExportOperations_Call) Run(run func(visitor exporter.Exporter, fileName string)) *DataService_ExportOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(exporter.Exporter), args[1].(string))
	})
	return _c
}

func (_c *DataService_ExportOperations_Call) Return(_a0 error) *DataService_ExportOperations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ExportOperations_Call) RunAndReturn(run func(exporter.Exporter, string) error) *DataService_ExportOperations_Call {
	_c.Call.Return(run)
	return _c
}

// ImportBankAccounts provides a mock function with given fields: visitor, fileName
func (_m *DataService) ImportBankAccounts(visitor importer.Importer, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ImportBankAccounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(importer.Importer, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ImportBankAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportBankAccounts'
type DataService_ImportBankAccounts_Call struct {
	*mock.Call
}

// ImportBankAccounts is a helper method to define mock.On call
//   - visitor importer.Importer
//   - fileName string
func (_e *DataService_Expecter) ImportBankAccounts(visitor interface{}, fileName interface{}) *DataService_ImportBankAccounts_Call {
	return &DataService_ImportBankAccounts_Call{Call: _e.mock.On("ImportBankAccounts", visitor, fileName)}
}

func (_c *DataService_ImportBankAccounts_Call) Run(run func(visitor importer.Importer, fileName string)) *DataService_ImportBankAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(importer.Importer), args[1].(string))
	})
	return _c
}

func (_c *DataService_ImportBankAccounts_Call) Return(_a0 error) *DataService_ImportBankAccounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ImportBankAccounts_Call) RunAndReturn(run func(importer.Importer, string) error) *DataService_ImportBankAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ImportCategories provides a mock function with given fields: visitor, fileName
func (_m *DataService) ImportCategories(visitor importer.Importer, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ImportCategories")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(importer.Importer, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ImportCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportCategories'
type DataService_ImportCategories_Call struct {
	*mock.Call
}

// ImportCategories is a helper method to define mock.On call
//   - visitor importer.Importer
//   - fileName string
func (_e *DataService_Expecter) ImportCategories(visitor interface{}, fileName interface{}) *DataService_ImportCategories_Call {
	return &DataService_ImportCategories_Call{Call: _e.mock.On("ImportCategories", visitor, fileName)}
}

func (_c *DataService_ImportCategories_Call) Run(run func(visitor importer.Importer, fileName string)) *DataService_ImportCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(importer.Importer), args[1].(string))
	})
	return _c
}

func (_c *DataService_ImportCategories_Call) Return(_a0 error) *DataService_ImportCategories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ImportCategories_Call) RunAndReturn(run func(importer.Importer, string) error) *DataService_ImportCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ImportOperations provides a mock function with given fields: visitor, fileName
func (_m *DataService) ImportOperations(visitor importer.Importer, fileName string) error {
	ret := _m.Called(visitor, fileName)

	if len(ret) == 0 {
		panic("no return value specified for ImportOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(importer.Importer, string) error); ok {
		r0 = rf(visitor, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataService_ImportOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportOperations'
type DataService_ImportOperations_Call struct {
	*mock.Call
}

// ImportOperations is a helper method to define mock.On call
//   - visitor importer.Importer
//   - fileName string
func (_e *DataService_Expecter) ImportOperations(visitor interface{}, fileName interface{}) *DataService_ImportOperations_Call {
	return &DataService_ImportOperations_Call{Call: _e.mock.On("ImportOperations", visitor, fileName)}
}

func (_c *DataService_ImportOperations_Call) Run(run func(visitor importer.Importer, fileName string)) *DataService_ImportOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(importer.Importer), args[1].(string))
	})
	return _c
}

func (_c *DataService_ImportOperations_Call) Return(_a0 error) *DataService_ImportOperations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataService_ImportOperations_Call) RunAndReturn(run func(importer.Importer, string) error) *DataService_ImportOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewDataService creates a new instance of DataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataService {
	mock := &DataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
