// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OperationService is an autogenerated mock type for the OperationService type
type OperationService struct {
	mock.Mock
}

type OperationService_Expecter struct {
	mock *mock.Mock
}

func (_m *OperationService) EXPECT() *OperationService_Expecter {
	return &OperationService_Expecter{mock: &_m.Mock}
}

// CreateOperation provides a mock function with given fields: op
func (_m *OperationService) CreateOperation(op *domain.Operation) error {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OperationService_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type OperationService_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - op *domain.Operation
func (_e *OperationService_Expecter) CreateOperation(op interface{}) *OperationService_CreateOperation_Call {
	return &OperationService_CreateOperation_Call{Call: _e.mock.On("CreateOperation", op)}
}

func (_c *OperationService_CreateOperation_Call) Run(run func(op *domain.Operation)) *OperationService_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *OperationService_CreateOperation_Call) Return(_a0 error) *OperationService_CreateOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OperationService_CreateOperation_Call) RunAndReturn(run func(*domain.Operation) error) *OperationService_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOperation provides a mock function with given fields: id
func (_m *OperationService) DeleteOperation(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OperationService_DeleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOperation'
type OperationService_DeleteOperation_Call struct {
	*mock.Call
}

// DeleteOperation is a helper method to define mock.On call
//   - id int
func (_e *OperationService_Expecter) DeleteOperation(id interface{}) *OperationService_DeleteOperation_Call {
	return &OperationService_DeleteOperation_Call{Call: _e.mock.On("DeleteOperation", id)}
}

func (_c *OperationService_DeleteOperation_Call) Run(run func(id int)) *OperationService_DeleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *OperationService_DeleteOperation_Call) Return(_a0 error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OperationService_DeleteOperation_Call) RunAndReturn(run func(int) error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function with given fields: id
func (_m *OperationService) GetOperation(id int) (*domain.Operation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Operation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Operation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationService_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type OperationService_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - id int
func (_e *OperationService_Expecter) GetOperation(id interface{}) *OperationService_GetOperation_Call {
	return &OperationService_GetOperation_Call{Call: _e.mock.On("GetOperation", id)}
}

func (_c *OperationService_GetOperation_Call) Run(run func(id int)) *OperationService_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *OperationService_GetOperation_Call) Return(_a0 *domain.Operation, _a1 error) *OperationService_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationService_GetOperation_Call) RunAndReturn(run func(int) (*domain.Operation, error)) *OperationService_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOperation provides a mock function with given fields: op
func (_m *OperationService) UpdateOperation(op *domain.Operation) error {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OperationService_UpdateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOperation'
type OperationService_UpdateOperation_Call struct {
	*mock.Call
}

// UpdateOperation is a helper method to define mock.On call
//   - op *domain.Operation
func (_e *OperationService_Expecter) UpdateOperation(op interface{}) *OperationService_UpdateOperation_Call {
	return &OperationService_UpdateOperation_Call{Call: _e.mock.On("UpdateOperation", op)}
}

func (_c *OperationService_UpdateOperation_Call) Run(run func(op *domain.Operation)) *OperationService_UpdateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *OperationService_UpdateOperation_Call) Return(_a0 error) *OperationService_UpdateOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OperationService_UpdateOperation_Call) RunAndReturn(run func(*domain.Operation) error) *OperationService_UpdateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewOperationService creates a new instance of OperationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationService {
	mock := &OperationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
