// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataParser is an autogenerated mock type for the DataParser type
type DataParser struct {
	mock.Mock
}

type DataParser_Expecter struct {
	mock *mock.Mock
}

func (_m *DataParser) EXPECT() *DataParser_Expecter {
	return &DataParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: data, v
func (_m *DataParser) Parse(data []byte, v interface{}) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type DataParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - data []byte
//   - v interface{}
func (_e *DataParser_Expecter) Parse(data interface{}, v interface{}) *DataParser_Parse_Call {
	return &DataParser_Parse_Call{Call: _e.mock.On("Parse", data, v)}
}

func (_c *DataParser_Parse_Call) Run(run func(data []byte, v interface{})) *DataParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(interface{}))
	})
	return _c
}

func (_c *DataParser_Parse_Call) Return(_a0 error) *DataParser_Parse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataParser_Parse_Call) RunAndReturn(run func([]byte, interface{}) error) *DataParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewDataParser creates a new instance of DataParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataParser {
	mock := &DataParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
