// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Exporter is an autogenerated mock type for the Exporter type
type Exporter struct {
	mock.Mock
}

type Exporter_Expecter struct {
	mock *mock.Mock
}

func (_m *Exporter) EXPECT() *Exporter_Expecter {
	return &Exporter_Expecter{mock: &_m.Mock}
}

// Export provides a mock function with given fields: fileName
func (_m *Exporter) Export(fileName string) error {
	ret := _m.Called(fileName)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type Exporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - fileName string
func (_e *Exporter_Expecter) Export(fileName interface{}) *Exporter_Export_Call {
	return &Exporter_Export_Call{Call: _e.mock.On("Export", fileName)}
}

func (_c *Exporter_Export_Call) Run(run func(fileName string)) *Exporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Exporter_Export_Call) Return(_a0 error) *Exporter_Export_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Exporter_Export_Call) RunAndReturn(run func(string) error) *Exporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// VisitBankAccount provides a mock function with given fields: account
func (_m *Exporter) VisitBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for VisitBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exporter_VisitBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitBankAccount'
type Exporter_VisitBankAccount_Call struct {
	*mock.Call
}

// VisitBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *Exporter_Expecter) VisitBankAccount(account interface{}) *Exporter_VisitBankAccount_Call {
	return &Exporter_VisitBankAccount_Call{Call: _e.mock.On("VisitBankAccount", account)}
}

func (_c *Exporter_VisitBankAccount_Call) Run(run func(account *domain.BankAccount)) *Exporter_VisitBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *Exporter_VisitBankAccount_Call) Return(_a0 error) *Exporter_VisitBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Exporter_VisitBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *Exporter_VisitBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// VisitCategory provides a mock function with given fields: category
func (_m *Exporter) VisitCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for VisitCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exporter_VisitCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitCategory'
type Exporter_VisitCategory_Call struct {
	*mock.Call
}

// VisitCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *Exporter_Expecter) VisitCategory(category interface{}) *Exporter_VisitCategory_Call {
	return &Exporter_VisitCategory_Call{Call: _e.mock.On("VisitCategory", category)}
}

func (_c *Exporter_VisitCategory_Call) Run(run func(category *domain.Category)) *Exporter_VisitCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *Exporter_VisitCategory_Call) Return(_a0 error) *Exporter_VisitCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Exporter_VisitCategory_Call) RunAndReturn(run func(*domain.Category) error) *Exporter_VisitCategory_Call {
	_c.Call.Return(run)
	return _c
}

// VisitOperation provides a mock function with given fields: operation
func (_m *Exporter) VisitOperation(operation *domain.Operation) error {
	ret := _m.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for VisitOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exporter_VisitOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitOperation'
type Exporter_VisitOperation_Call struct {
	*mock.Call
}

// VisitOperation is a helper method to define mock.On call
//   - operation *domain.Operation
func (_e *Exporter_Expecter) VisitOperation(operation interface{}) *Exporter_VisitOperation_Call {
	return &Exporter_VisitOperation_Call{Call: _e.mock.On("VisitOperation", operation)}
}

func (_c *Exporter_VisitOperation_Call) Run(run func(operation *domain.Operation)) *Exporter_VisitOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *Exporter_VisitOperation_Call) Return(_a0 error) *Exporter_VisitOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Exporter_VisitOperation_Call) RunAndReturn(run func(*domain.Operation) error) *Exporter_VisitOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewExporter creates a new instance of Exporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Exporter {
	mock := &Exporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
