// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ExportVisitor is an autogenerated mock type for the ExportVisitor type
type ExportVisitor struct {
	mock.Mock
}

type ExportVisitor_Expecter struct {
	mock *mock.Mock
}

func (_m *ExportVisitor) EXPECT() *ExportVisitor_Expecter {
	return &ExportVisitor_Expecter{mock: &_m.Mock}
}

// VisitBankAccount provides a mock function with given fields: account
func (_m *ExportVisitor) VisitBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for VisitBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExportVisitor_VisitBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitBankAccount'
type ExportVisitor_VisitBankAccount_Call struct {
	*mock.Call
}

// VisitBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *ExportVisitor_Expecter) VisitBankAccount(account interface{}) *ExportVisitor_VisitBankAccount_Call {
	return &ExportVisitor_VisitBankAccount_Call{Call: _e.mock.On("VisitBankAccount", account)}
}

func (_c *ExportVisitor_VisitBankAccount_Call) Run(run func(account *domain.BankAccount)) *ExportVisitor_VisitBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *ExportVisitor_VisitBankAccount_Call) Return(_a0 error) *ExportVisitor_VisitBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExportVisitor_VisitBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *ExportVisitor_VisitBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// VisitCategory provides a mock function with given fields: category
func (_m *ExportVisitor) VisitCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for VisitCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExportVisitor_VisitCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitCategory'
type ExportVisitor_VisitCategory_Call struct {
	*mock.Call
}

// VisitCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *ExportVisitor_Expecter) VisitCategory(category interface{}) *ExportVisitor_VisitCategory_Call {
	return &ExportVisitor_VisitCategory_Call{Call: _e.mock.On("VisitCategory", category)}
}

func (_c *ExportVisitor_VisitCategory_Call) Run(run func(category *domain.Category)) *ExportVisitor_VisitCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *ExportVisitor_VisitCategory_Call) Return(_a0 error) *ExportVisitor_VisitCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExportVisitor_VisitCategory_Call) RunAndReturn(run func(*domain.Category) error) *ExportVisitor_VisitCategory_Call {
	_c.Call.Return(run)
	return _c
}

// VisitOperation provides a mock function with given fields: operation
func (_m *ExportVisitor) VisitOperation(operation *domain.Operation) error {
	ret := _m.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for VisitOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExportVisitor_VisitOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitOperation'
type ExportVisitor_VisitOperation_Call struct {
	*mock.Call
}

// VisitOperation is a helper method to define mock.On call
//   - operation *domain.Operation
func (_e *ExportVisitor_Expecter) VisitOperation(operation interface{}) *ExportVisitor_VisitOperation_Call {
	return &ExportVisitor_VisitOperation_Call{Call: _e.mock.On("VisitOperation", operation)}
}

func (_c *ExportVisitor_VisitOperation_Call) Run(run func(operation *domain.Operation)) *ExportVisitor_VisitOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *ExportVisitor_VisitOperation_Call) Return(_a0 error) *ExportVisitor_VisitOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExportVisitor_VisitOperation_Call) RunAndReturn(run func(*domain.Operation) error) *ExportVisitor_VisitOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewExportVisitor creates a new instance of ExportVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExportVisitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExportVisitor {
	mock := &ExportVisitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
