// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/AFK068/bot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// DeleteBankAccount provides a mock function with given fields: id
func (_m *Repository) DeleteBankAccount(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBankAccount'
type Repository_DeleteBankAccount_Call struct {
	*mock.Call
}

// DeleteBankAccount is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) DeleteBankAccount(id interface{}) *Repository_DeleteBankAccount_Call {
	return &Repository_DeleteBankAccount_Call{Call: _e.mock.On("DeleteBankAccount", id)}
}

func (_c *Repository_DeleteBankAccount_Call) Run(run func(id int)) *Repository_DeleteBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_DeleteBankAccount_Call) Return(_a0 error) *Repository_DeleteBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteBankAccount_Call) RunAndReturn(run func(int) error) *Repository_DeleteBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: id
func (_m *Repository) DeleteCategory(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type Repository_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) DeleteCategory(id interface{}) *Repository_DeleteCategory_Call {
	return &Repository_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", id)}
}

func (_c *Repository_DeleteCategory_Call) Run(run func(id int)) *Repository_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_DeleteCategory_Call) Return(_a0 error) *Repository_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteCategory_Call) RunAndReturn(run func(int) error) *Repository_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOperation provides a mock function with given fields: id
func (_m *Repository) DeleteOperation(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOperation'
type Repository_DeleteOperation_Call struct {
	*mock.Call
}

// DeleteOperation is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) DeleteOperation(id interface{}) *Repository_DeleteOperation_Call {
	return &Repository_DeleteOperation_Call{Call: _e.mock.On("DeleteOperation", id)}
}

func (_c *Repository_DeleteOperation_Call) Run(run func(id int)) *Repository_DeleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_DeleteOperation_Call) Return(_a0 error) *Repository_DeleteOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteOperation_Call) RunAndReturn(run func(int) error) *Repository_DeleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBankAccounts provides a mock function with no fields
func (_m *Repository) GetAllBankAccounts() ([]*domain.BankAccount, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllBankAccounts")
	}

	var r0 []*domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.BankAccount, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.BankAccount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllBankAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBankAccounts'
type Repository_GetAllBankAccounts_Call struct {
	*mock.Call
}

// GetAllBankAccounts is a helper method to define mock.On call
func (_e *Repository_Expecter) GetAllBankAccounts() *Repository_GetAllBankAccounts_Call {
	return &Repository_GetAllBankAccounts_Call{Call: _e.mock.On("GetAllBankAccounts")}
}

func (_c *Repository_GetAllBankAccounts_Call) Run(run func()) *Repository_GetAllBankAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetAllBankAccounts_Call) Return(_a0 []*domain.BankAccount, _a1 error) *Repository_GetAllBankAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllBankAccounts_Call) RunAndReturn(run func() ([]*domain.BankAccount, error)) *Repository_GetAllBankAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function with no fields
func (_m *Repository) GetAllCategories() ([]*domain.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []*domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type Repository_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
func (_e *Repository_Expecter) GetAllCategories() *Repository_GetAllCategories_Call {
	return &Repository_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories")}
}

func (_c *Repository_GetAllCategories_Call) Run(run func()) *Repository_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetAllCategories_Call) Return(_a0 []*domain.Category, _a1 error) *Repository_GetAllCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllCategories_Call) RunAndReturn(run func() ([]*domain.Category, error)) *Repository_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOperations provides a mock function with no fields
func (_m *Repository) GetAllOperations() ([]*domain.Operation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllOperations")
	}

	var r0 []*domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.Operation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.Operation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAllOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOperations'
type Repository_GetAllOperations_Call struct {
	*mock.Call
}

// GetAllOperations is a helper method to define mock.On call
func (_e *Repository_Expecter) GetAllOperations() *Repository_GetAllOperations_Call {
	return &Repository_GetAllOperations_Call{Call: _e.mock.On("GetAllOperations")}
}

func (_c *Repository_GetAllOperations_Call) Run(run func()) *Repository_GetAllOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetAllOperations_Call) Return(_a0 []*domain.Operation, _a1 error) *Repository_GetAllOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAllOperations_Call) RunAndReturn(run func() ([]*domain.Operation, error)) *Repository_GetAllOperations_Call {
	_c.Call.Return(run)
	return _c
}

// GetBankAccount provides a mock function with given fields: id
func (_m *Repository) GetBankAccount(id int) (*domain.BankAccount, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBankAccount")
	}

	var r0 *domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.BankAccount, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.BankAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBankAccount'
type Repository_GetBankAccount_Call struct {
	*mock.Call
}

// GetBankAccount is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) GetBankAccount(id interface{}) *Repository_GetBankAccount_Call {
	return &Repository_GetBankAccount_Call{Call: _e.mock.On("GetBankAccount", id)}
}

func (_c *Repository_GetBankAccount_Call) Run(run func(id int)) *Repository_GetBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_GetBankAccount_Call) Return(_a0 *domain.BankAccount, _a1 error) *Repository_GetBankAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetBankAccount_Call) RunAndReturn(run func(int) (*domain.BankAccount, error)) *Repository_GetBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function with given fields: id
func (_m *Repository) GetCategory(id int) (*domain.Category, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type Repository_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) GetCategory(id interface{}) *Repository_GetCategory_Call {
	return &Repository_GetCategory_Call{Call: _e.mock.On("GetCategory", id)}
}

func (_c *Repository_GetCategory_Call) Run(run func(id int)) *Repository_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_GetCategory_Call) Return(_a0 *domain.Category, _a1 error) *Repository_GetCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetCategory_Call) RunAndReturn(run func(int) (*domain.Category, error)) *Repository_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function with given fields: id
func (_m *Repository) GetOperation(id int) (*domain.Operation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Operation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Operation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type Repository_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - id int
func (_e *Repository_Expecter) GetOperation(id interface{}) *Repository_GetOperation_Call {
	return &Repository_GetOperation_Call{Call: _e.mock.On("GetOperation", id)}
}

func (_c *Repository_GetOperation_Call) Run(run func(id int)) *Repository_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_GetOperation_Call) Return(_a0 *domain.Operation, _a1 error) *Repository_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetOperation_Call) RunAndReturn(run func(int) (*domain.Operation, error)) *Repository_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationsByAccountID provides a mock function with given fields: accountID
func (_m *Repository) GetOperationsByAccountID(accountID int) ([]*domain.Operation, error) {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationsByAccountID")
	}

	var r0 []*domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*domain.Operation, error)); ok {
		return rf(accountID)
	}
	if rf, ok := ret.Get(0).(func(int) []*domain.Operation); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetOperationsByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationsByAccountID'
type Repository_GetOperationsByAccountID_Call struct {
	*mock.Call
}

// GetOperationsByAccountID is a helper method to define mock.On call
//   - accountID int
func (_e *Repository_Expecter) GetOperationsByAccountID(accountID interface{}) *Repository_GetOperationsByAccountID_Call {
	return &Repository_GetOperationsByAccountID_Call{Call: _e.mock.On("GetOperationsByAccountID", accountID)}
}

func (_c *Repository_GetOperationsByAccountID_Call) Run(run func(accountID int)) *Repository_GetOperationsByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Repository_GetOperationsByAccountID_Call) Return(_a0 []*domain.Operation, _a1 error) *Repository_GetOperationsByAccountID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetOperationsByAccountID_Call) RunAndReturn(run func(int) ([]*domain.Operation, error)) *Repository_GetOperationsByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBankAccount provides a mock function with given fields: account
func (_m *Repository) SaveBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for SaveBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SaveBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBankAccount'
type Repository_SaveBankAccount_Call struct {
	*mock.Call
}

// SaveBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *Repository_Expecter) SaveBankAccount(account interface{}) *Repository_SaveBankAccount_Call {
	return &Repository_SaveBankAccount_Call{Call: _e.mock.On("SaveBankAccount", account)}
}

func (_c *Repository_SaveBankAccount_Call) Run(run func(account *domain.BankAccount)) *Repository_SaveBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *Repository_SaveBankAccount_Call) Return(_a0 error) *Repository_SaveBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SaveBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *Repository_SaveBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCategory provides a mock function with given fields: category
func (_m *Repository) SaveCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for SaveCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SaveCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCategory'
type Repository_SaveCategory_Call struct {
	*mock.Call
}

// SaveCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *Repository_Expecter) SaveCategory(category interface{}) *Repository_SaveCategory_Call {
	return &Repository_SaveCategory_Call{Call: _e.mock.On("SaveCategory", category)}
}

func (_c *Repository_SaveCategory_Call) Run(run func(category *domain.Category)) *Repository_SaveCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *Repository_SaveCategory_Call) Return(_a0 error) *Repository_SaveCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SaveCategory_Call) RunAndReturn(run func(*domain.Category) error) *Repository_SaveCategory_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOperation provides a mock function with given fields: op
func (_m *Repository) SaveOperation(op *domain.Operation) error {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for SaveOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SaveOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOperation'
type Repository_SaveOperation_Call struct {
	*mock.Call
}

// SaveOperation is a helper method to define mock.On call
//   - op *domain.Operation
func (_e *Repository_Expecter) SaveOperation(op interface{}) *Repository_SaveOperation_Call {
	return &Repository_SaveOperation_Call{Call: _e.mock.On("SaveOperation", op)}
}

func (_c *Repository_SaveOperation_Call) Run(run func(op *domain.Operation)) *Repository_SaveOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *Repository_SaveOperation_Call) Return(_a0 error) *Repository_SaveOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SaveOperation_Call) RunAndReturn(run func(*domain.Operation) error) *Repository_SaveOperation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBankAccount provides a mock function with given fields: account
func (_m *Repository) UpdateBankAccount(account *domain.BankAccount) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBankAccount'
type Repository_UpdateBankAccount_Call struct {
	*mock.Call
}

// UpdateBankAccount is a helper method to define mock.On call
//   - account *domain.BankAccount
func (_e *Repository_Expecter) UpdateBankAccount(account interface{}) *Repository_UpdateBankAccount_Call {
	return &Repository_UpdateBankAccount_Call{Call: _e.mock.On("UpdateBankAccount", account)}
}

func (_c *Repository_UpdateBankAccount_Call) Run(run func(account *domain.BankAccount)) *Repository_UpdateBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.BankAccount))
	})
	return _c
}

func (_c *Repository_UpdateBankAccount_Call) Return(_a0 error) *Repository_UpdateBankAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateBankAccount_Call) RunAndReturn(run func(*domain.BankAccount) error) *Repository_UpdateBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: category
func (_m *Repository) UpdateCategory(category *domain.Category) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type Repository_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - category *domain.Category
func (_e *Repository_Expecter) UpdateCategory(category interface{}) *Repository_UpdateCategory_Call {
	return &Repository_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", category)}
}

func (_c *Repository_UpdateCategory_Call) Run(run func(category *domain.Category)) *Repository_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Category))
	})
	return _c
}

func (_c *Repository_UpdateCategory_Call) Return(_a0 error) *Repository_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateCategory_Call) RunAndReturn(run func(*domain.Category) error) *Repository_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOperation provides a mock function with given fields: op
func (_m *Repository) UpdateOperation(op *domain.Operation) error {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Operation) error); ok {
		r0 = rf(op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOperation'
type Repository_UpdateOperation_Call struct {
	*mock.Call
}

// UpdateOperation is a helper method to define mock.On call
//   - op *domain.Operation
func (_e *Repository_Expecter) UpdateOperation(op interface{}) *Repository_UpdateOperation_Call {
	return &Repository_UpdateOperation_Call{Call: _e.mock.On("UpdateOperation", op)}
}

func (_c *Repository_UpdateOperation_Call) Run(run func(op *domain.Operation)) *Repository_UpdateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Operation))
	})
	return _c
}

func (_c *Repository_UpdateOperation_Call) Return(_a0 error) *Repository_UpdateOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateOperation_Call) RunAndReturn(run func(*domain.Operation) error) *Repository_UpdateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
